/** Reexporta contratos de domínio (espelho do antigo `src/types/protesto.ts`). */
export * from "./GFeriado/GFeriadoInterface";
export * from "./GUsuario/GUsuarioInterface";
export * from "./PArquivoTitulo/PArquivoTituloInterface";
export * from "./PBanco/PBancoInterface";
export * from "./PPessoaVinculo/PPessoaVinculoInterface";
export * from "./PPessoa/PPessoaInterface";
export * from "./PLivroNatureza/PLivroNaturezaInterface";
export * from "./PLivroAndamento/PLivroAndamentoInterface";
export * from "./PCustasCancelamento/PCustasCancelamentoInterface";
export * from "./GEmolumentoItem/GEmolumentoItemInterface";
export * from "./GEmolumento/GEmolumentoInterface";
export * from "./POcorrenciaAndamento/POcorrenciaAndamentoInterface";
export * from "./PMotivosCancelamento/PMotivosCancelamentoInterface";
export * from "./PMotivos/PMotivosInterface";
export * from "./POcorrencias/POcorrenciasInterface";
export * from "./PEspecie/PEspecieInterface";
export * from "./PTitulo/PTituloInterface";
export * from "./PTitulo/PTituloListItem";
