export const ImovelTipoEnum: { [key: number]: string } = {
  15: 'Loja',
  31: 'Galpão',
  65: 'Apartamento',
  67: 'Casa',
  69: 'Fazenda / Sítio / Chácara',
  71: 'Terreno / Fração',
  89: 'Outros',
  90: 'Sala',
  91: 'Conjunto de salas',
  92: 'Sobreloja',
  17: 'Sala / Conjunto',
  33: 'Prédio Comercial',
  35: 'Prédio Residencial',
  73: 'Sala ou Loja',
  85: 'Construções',
  87: 'Desmembramento',
  93: 'Vaga de Garagem',
  94: 'Laje',
  95: 'Estacionamento',
  96: 'Barraco',
};
