/**
 * Interface gerada para a tabela P_TITULO
 */
export type PTituloTipoAceite = "E" | "A";

export type PTituloTipoEndosso = "M" | "T";

export type PTituloStatusImportacao = "D" | "E";

export interface PTituloInterface {
  titulo_id: number;
  data_apontamento?: Date;
  data_aceite?: Date;
  valor_titulo?: number;
  data_protesto?: Date;
  data_cancelamento?: Date;
  especie_id?: number;
  ocorrencia_id?: number;
  numero_titulo?: string;
  data_vencimento_titulo?: Date;
  data_emissao_titulo?: Date;
  motivo_apontamento_id?: number;
  tabela_emolumento_id?: number;
  valor_emolumento?: number;
  valor_taxa_judiciaria?: number;
  valor_taxa_intimacao?: number;
  valor_desconto?: number;
  valor_taxa_edital?: number;
  valor_taxa_juros?: number;
  numero_apontamento?: number;
  data_cadastro?: Date;
  motivo_cancelamento?: number;
  data_sustado?: Date;
  folha_apontamento?: number;
  livro_id_apontamento?: number;
  user_assina_prot?: number;
  livro_id_protesto?: number;
  folha_protesto?: number;
  user_assina_apont?: number;
  data_pago?: Date;
  valor_taxa_correios?: number;
  data_env_serasa?: Date;
  data_ret_serasa?: Date;
  valor_taxa_cancel?: number;
  valor_taxa_averb?: number;
  data_desistencia?: Date;
  numero_cancelamento?: number;
  numero_protesto?: number;
  numero_ar?: string;
  taxa_correcao?: number;
  numero_titulo_banco?: string;
  data_mov_serasa?: Date;
  nosso_numero?: string;
  valor_taxa_fundesp?: number;
  emolumento_item_id?: number;
  data_intimacao?: Date;
  data_vencimento_boleto?: Date;
  valor_total?: number;
  valor_iss?: number;
  nlote?: number;
  valor_total_custas?: number;
  banco_id?: number;
  agencia_centralizadora?: string;
  codigo_praca?: string;
  local_aceite?: string;
  observacoes?: string;
  situacao_aceite?: string;
  pessoa_aceitou?: string;
  agencia_correio?: string;
  praca_pagamento?: string;
  motivo_isencao?: string;
  prazo?: string;
  tipo_aceite?: PTituloTipoAceite;
  numero_livro_apont?: string;
  tipo_endosso?: PTituloTipoEndosso;
  cobrar_juros?: string;
  letra_folha?: string;
  pagamento_posterior?: string;
  servico_gratuito?: string;
  pagamento_diferido?: string;
  titulo_antigo?: string;
  forma_pagamento?: string;
  agencia_codigo_cedente?: string;
  status_importacao?: PTituloStatusImportacao;
  protestado?: string;
  selecao_status?: string;
  importar?: string;
  nfse_id?: number;
  data_retorno_cda?: Date;
  arquivo_titulo_id?: number;
  email?: string;
  data_anuencia?: Date;
  origem_anuencia?: string;
  apresentante_permitido?: string;
  cedente_permitido?: string;
  credor_permitido?: string;
  anuencia?: string;
  situacao_cenprot?: string;
  custas_cancelamento_id?: number;
  livro_pagamento?: number;
  letra_livro_pagamento?: string;
  folha_livro_pagamento?: number;
  chave_unica_cenprot?: string;
  protesto_artigo_9?: string;
  chave_importacao?: number;
  impsituacao_titulo?: string;
  ocorrencia_andamento_id?: number;
}
